server:
  port: 8082
spring:
  data:
    solr:
      host: http://192.168.226.160:8080/solr
  thymeleaf:
    cache: false
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.226.160:2181
  consumer:
    check: false
image:
  path: http://192.168.226.160/