server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath*:com/qf/shop/shop_kill/dao/mapper/*.xml
  type-aliases-package: com.qf.entity