server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 10MB
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.226.160:2181
fdfs:
  connect-timeout: 60
  pool:
    jmx-enabled: false
  thumb-image:
    height: 200
    width: 200
  tracker-list: 192.168.226.160:22122
image:
  path: http://192.168.226.160/